drop database if exists rwscrapper;
create database rwscrapper character set utf8 collate utf8_general_ci;

use mysql;

delimiter $$

drop procedure if exists `DropUserIfExists`$$

create definer=`root`@`localhost` procedure `DropUserIfExists`(
    MyUserName VARCHAR(100), 
    MyHostName VARCHAR(100)
)
begin
    declare pDone int default 0;
    declare mUser varchar(100);
    declare  mHost varchar(100);
    declare recUserCursor CURSOR FOR
    select `User`, `Host` from `mysql`.`user` where `User` = MyUserName;
    declare continue handler for not found set pDone = 1;

    if (MyHostName is not null) then
        -- 'username'@'hostname' exists
        if (exists(select null FROM `mysql`.`user` where `User` = MyUserName AND `Host` = MyHostName)) then
            set @SQL = (select mResult from (select group_concat("drop user ", "'", MyUserName, "'@'", MyHostName, "'") as mResult) as Q LIMIT 1);
            prepare stmt from @SQL;
            execute stmt;
            deallocate prepare stmt;
        end if;
    else
        -- check whether MyUserName exists (MyUserName@'%' , MyUserName@'localhost' etc)
        open recUserCursor;
        repeat
        fetch recUserCursor into mUser, mHost;
        if not pDone then
            set @SQL = (select mResult from (select group_concat("drop user ", "'", mUser, "'@'", mHost, "'") as mResult) as Q LIMIT 1);
            prepare stmt from @SQL;
            execute stmt;
            deallocate prepare stmt;
        end if;
        until pDone end repeat;
    end if;
    flush privileges;
    end$$

delimiter ;

call `DropUserIfExists`('scrapper', 'localhost');
create user 'scrapper'@'localhost' identified by 'scrapper';

use rwscrapper;

grant all on rwscrapper.* to 'scrapper'@'localhost';
grant all on DEX.* to 'scrapper'@'localhost';
grant super on *.* to 'scrapper'@'localhost';

drop table if exists `Texts`;
create table `Texts` (
    `id` int not null auto_increment,
    `url` char(200) not null,
    `canonicalUrl` char(200) not null,
    `contentFile` text character set utf8 not null,
    `trigramError` float(4,2) not null,
    `bigramError` float(4,2) not null,
    `unigramError` float(4, 2) not null,
    `freqError` float(4, 2) not null,
    `averageWordLength` float(5, 2) not null,
    `romanianScore` float(4, 2) not null,
    `sourceType` int(11) not null,
    `createDate` int(11) not null,
    `noDia` int(11) not null,
    primary key(`id`),
    index(`id`)
);

drop table if exists `Phrases`;
create table `Phrases` (
    `id` int(11) not null auto_increment,
    `textId` int not null,
    `phraseContent` text character set utf8 not null,
    `romanianScore` float(11,2),
    primary key(`id`),
    foreign key(`textId`) references Texts(`id`),
    index(`id`)
);

drop table if exists `Prefixes`;
create table `Prefixes` (
    `id` int(11) not null auto_increment,
    `form` char(20) collate utf8_romanian_ci not null,
    `formUtf8General` char(20) character set utf8 not null,
    `prefixLength` int(11) not null,
    `meaning` text collate utf8_romanian_ci,
    primary key(`id`),
    index(`id`),
    index(`form`)
);

drop table if exists `Suffixes`;
create table `Suffixes` (
    `id` int(11) not null auto_increment,
    `form` char(20) collate utf8_romanian_ci not null,
    `formUtf8General` char(20) character set utf8 not null,
    `suffixLength` int(11) not null,
    `meaning` text collate utf8_romanian_ci,
    primary key(`id`),
    index(`id`),
    index(`form`)
);

drop table if exists `Domains`;
create table `Domains` (
    id int(11) not null auto_increment,
    name char(100) collate utf8_romanian_ci not null,
    primary key(`id`),
    index(`id`),
    index(`name`)
);


drop table if exists `Words`;
create table `Words` (
    `id` int(11) not null auto_increment,
    `phraseId` int(11) not null,
    `form` char(100) collate utf8_romanian_ci not null,
    `formUtf8General` char(100) character set utf8 not null,
    `reverse` char(100) collate utf8_romanian_ci not null,
    `charLength` int(11) not null,
    `createDate` int(11) not null,
    `etymology` varchar(50),
    `suffixId` int(11),
    `prefixId` int(11),
    `domainId` int(11),
    `definition` text collate utf8_romanian_ci,
    primary key(`id`),
    foreign key(`phraseId`) references Phrases(`id`),
    foreign key(`prefixId`) references Prefixes(`id`),
    foreign key(`suffixId`) references Suffixes(`id`),
    foreign key(`domainId`) references Domains(`id`),
    index(`id`),
    index(`form`)
);

drop table if exists `Inflections`;
create table `Inflections` (
    `id` int(11) not null auto_increment,
    `description` varchar(255) collate utf8_romanian_ci not null,
    `shortForm` varchar(10),
    primary key(`id`),
    index(`id`)
);

drop table if exists `InflectedForms`;
create table `InflectedForms` (
    `id` int(11) not null auto_increment,
    `wordId` int(11) not null,
    `inflectionId` int(11) not null,
    `form` char(100) collate utf8_romanian_ci not null,
    `formUtf8General` char(100) character set utf8 not null,
    `noApp` int(11) default 1,
    primary key(`id`),
    foreign key(`wordId`) references Words(`id`),
    foreign key(`inflectionId`) references Inflections(`id`),
    index(`id`),
    index(`form`)
);

drop table if exists `Clitics`;
create table `Clitics` (
    `id` int(11) not null auto_increment,
    `form` char(100) collate utf8_romanian_ci not null,
    `formNoHyphen` char(100) collate utf8_romanian_ci not null,
    `formNoDia` char(100) not null,
    primary key(`id`),
    index(`id`),
    index(`form`)
);

drop table if exists `CliticTokens`;
create table `CliticTokens` (
    `id` int(11) not null auto_increment,
    `form` char(100) collate utf8_romanian_ci not null,
    `formNoDia` char(100) not null,
    primary key(`id`),
    index(`id`),
    index(`form`)
);

lock tables `Inflections` write;
insert into `Inflections` (`id`, `description`, `shortForm`) values
(1, 'Substantiv masculin, Nominativ-Acuzativ, singular, nearticulat', 'SM'),
(2, 'Substantiv masculin, Genitiv-Dativ, singular, nearticulat', 'SM'),
(3, 'Substantiv masculin, Nominativ-Acuzativ, plural, nearticulat', 'SM'),
(4, 'Substantiv masculin, Genitiv-Dativ, plural, nearticulat', 'SM'),
(5, 'Substantiv masculin, Nominativ-Acuzativ, singular, articulat', 'SM'),
(6, 'Substantiv masculin, Genitiv-Dativ, singular, articulat', 'SM'),
(7, 'Substantiv masculin, Nominativ-Acuzativ, plural, articulat', 'SM'),
(8, 'Substantiv masculin, Genitiv-Dativ, plural, articulat', 'SM'),
(9, 'Substantiv feminin, Nominativ-Acuzativ, singular, nearticulat', 'SF'),
(10, 'Substantiv feminin, Genitiv-Dativ, singular, nearticulat', 'SF'),
(11, 'Substantiv feminin, Nominativ-Acuzativ, plural, nearticulat', 'SF'),
(12, 'Substantiv feminin, Genitiv-Dativ, plural, nearticulat', 'SF'),
(13, 'Substantiv feminin, Nominativ-Acuzativ, singular, articulat', 'SF'),
(14, 'Substantiv feminin, Genitiv-Dativ, singular, articulat', 'SF'),
(15, 'Substantiv feminin, Nominativ-Acuzativ, plural, articulat', 'SF'),
(16, 'Substantiv feminin, Genitiv-Dativ, plural, articulat', 'SF'),
(17, 'Substantiv neutru, Nominativ-Acuzativ, singular, nearticulat', 'SN'),
(18, 'Substantiv neutru, Genitiv-Dativ, singular, nearticulat', 'SN'),
(19, 'Substantiv neutru, Nominativ-Acuzativ, plural, nearticulat', 'SN'),
(20, 'Substantiv neutru, Genitiv-Dativ, plural, nearticulat', 'SN'),
(21, 'Substantiv neutru, Nominativ-Acuzativ, singular, articulat', 'SN'),
(22, 'Substantiv neutru, Genitiv-Dativ, singular, articulat', 'SN'),
(23, 'Substantiv neutru, Nominativ-Acuzativ, plural, articulat', 'SN'),
(24, 'Substantiv neutru, Genitiv-Dativ, plural, articulat', 'SN'),
(25, 'Adjectiv masculin, Nominativ-Acuzativ, singular, nearticulat', 'ADJM'),
(26, 'Adjectiv masculin, Genitiv-Dativ, singular, nearticulat', 'ADJM'),
(27, 'Adjectiv masculin, Nominativ-Acuzativ, plural, nearticulat', 'ADJM'),
(28, 'Adjectiv masculin, Genitiv-Dativ, plural, nearticulat', 'ADJM'),
(29, 'Adjectiv masculin, Nominativ-Acuzativ, singular, articulat', 'ADJM'),
(30, 'Adjectiv masculin, Genitiv-Dativ, singular, articulat', 'ADJM'),
(31, 'Adjectiv masculin, Nominativ-Acuzativ, plural, articulat', 'ADJM'),
(32, 'Adjectiv masculin, Genitiv-Dativ, plural, articulat', 'ADJM'),
(33, 'Adjectiv feminin, Nominativ-Acuzativ, singular, nearticulat', 'ADJF'),
(34, 'Adjectiv feminin, Genitiv-Dativ, singular, nearticulat', 'ADJF'),
(35, 'Adjectiv feminin, Nominativ-Acuzativ, plural, nearticulat', 'ADJF'),
(36, 'Adjectiv feminin, Genitiv-Dativ, plural, nearticulat', 'ADJF'),
(37, 'Adjectiv feminin, Nominativ-Acuzativ, singular, articulat', 'ADJF'),
(38, 'Adjectiv feminin, Genitiv-Dativ, singular, articulat', 'ADJF'),
(39, 'Adjectiv feminin, Nominativ-Acuzativ, plural, articulat', 'ADJF'),
(40, 'Adjectiv feminin, Genitiv-Dativ, plural, articulat', 'ADJF'),
(41, 'Pronume, Nominativ-Acuzativ, singular, masculin', 'PM'),
(42, 'Pronume, Genitiv-Dativ, singular, masculin', 'PM'),
(43, 'Pronume, Nominativ-Acuzativ, plural, masculin', 'PM'),
(44, 'Pronume, Genitiv-Dativ, plural, feminin', 'PF'),
(45, 'Pronume, Nominativ-Acuzativ, singular, feminin', 'PF'),
(46, 'Pronume, Genitiv-Dativ, singular, feminin', 'PF'),
(47, 'Pronume, Nominativ-Acuzativ, plural, feminin', 'PF'),
(48, 'Pronume, Genitiv-Dativ, plural, feminin', 'PF'),
(49, 'Verb, Infinitiv prezent', 'VB'),
(50, 'Verb, Infinitiv lung', 'VB'),
(51, 'Verb, Imperativ, persoana a II-a, singular', 'VB'),
(52, 'Verb, Participiu pasiv', 'VB'),
(53, 'Verb, Gerunziu', 'VB'),
(54, 'Verb, Indicativ, prezent, persoana I, singular', 'VB'),
(55, 'Verb, Indicativ, prezent, persoana a II-a, singular', 'VB'),
(56, 'Verb, Indicativ, prezent, persoana a III-a, singular', 'VB'),
(57, 'Verb, Indicativ, prezent, persoana I, plural', 'VB'),
(58, 'Verb, Indicativ, prezent, persoana a II-a, plural', 'VB'),
(59, 'Verb, Indicativ, prezent, persoana a III-a, plural', 'VB'),
(60, 'Verb, Conjunctiv, prezent, persoana I, singular', 'VB'),
(61, 'Verb, Conjunctiv, prezent, persoana a II-a, singular', 'VB'),
(62, 'Verb, Conjunctiv, prezent, persoana a III-a, singular', 'VB'),
(63, 'Verb, Conjunctiv, prezent, persoana I, plural', 'VB'),
(64, 'Verb, Conjunctiv, prezent, persoana a II-a, plural', 'VB'),
(65, 'Verb, Conjunctiv, prezent, persoana a III-a, plural', 'VB'),
(66, 'Verb, Indicativ, imperfect, persoana I, singular', 'VB'),
(67, 'Verb, Indicativ, imperfect, persoana a II-a, singular', 'VB'),
(68, 'Verb, Indicativ, imperfect, persoana a III-a, singular', 'VB'),
(69, 'Verb, Indicativ, imperfect, persoana I, plural', 'VB'),
(70, 'Verb, Indicativ, imperfect, persoana a II-a, plural', 'VB'),
(71, 'Verb, Indicativ, imperfect, persoana a III-a, plural', 'VB'),
(72, 'Verb, Indicativ, perfect simplu, persoana I, singular', 'VB'),
(73, 'Verb, Indicativ, perfect simplu, persoana a II-a, singular', 'VB'),
(74, 'Verb, Indicativ, perfect simplu, persoana a III-a, singular', 'VB'),
(75, 'Verb, Indicativ, perfect simplu, persoana I, plural', 'VB'),
(76, 'Verb, Indicativ, perfect simplu, persoana a II-a, plural', 'VB'),
(77, 'Verb, Indicativ, perfect simplu, persoana a III-a, plural', 'VB'),
(78, 'Verb, Indicativ, mai mult ca perfect, persoana I, singular', 'VB'),
(79, 'Verb, Indicativ, mai mult ca perfect, persoana a II-a, singular', 'VB'),
(80, 'Verb, Indicativ, mai mult ca perfect, persoana a III-a, singular', 'VB'),
(81, 'Verb, Indicativ, mai mult ca perfect, persoana I, plural', 'VB'),
(82, 'Verb, Indicativ, mai mult ca perfect, persoana a II-a, plural', 'VB'),
(83, 'Verb, Indicativ, mai mult ca perfect, persoana a III-a, plural', 'VB'),
(84, 'Verb, Imperativ, persoana a II-a, plural', 'VB'),
(85, 'Substantiv, Vocativ, singular, masculin', 'SM'),
(86, 'Substantiv, Vocativ, plural, masculin', 'SM'),
(87, 'Substantiv, Vocativ, singular, feminin', 'SF'),
(88, 'Substantiv, Vocativ, plural, feminin', 'SF'),
(89, 'Substantiv, Vocativ, singular, neutru', 'SN'),
(90, 'Substantiv, Vocativ, plural, neutru', 'SN'),
(91, 'Adjectiv, Vocativ, singular, masculin', 'ADJM'),
(92, 'Adjectiv, Vocativ, plural, masculin', 'ADJM'),
(93, 'Adjectiv, Vocativ, singular, feminin', 'ADJF'),
(94, 'Adjectiv, Vocativ, plural, feminin', 'ADJF'),
(95, 'Adverb', 'ADV'),
(96, 'Prepoziție', 'PREP'),
(97, 'Conjuncție', 'CONJ'),
(98, 'Interjecție', 'INTERJ'),
(99, 'Adjectiv invariabil', 'ADJI'),
(100, 'Articol hotărât', 'ART'),
(101, 'Articol nehotărât', 'ART'),
(102, 'N/A', 'NA'),
(103, 'Substantiv propriu, Nominativ-Acuzativ, singular, nearticulat', 'SP'),
(104, 'Substantiv propriu, Genitiv-Dativ, singular, nearticulat', 'SP'),
(105, 'Substantiv propriu, Nominativ-Acuzativ, plural, nearticulat', 'SP'),
(106, 'Substantiv propriu, Genitiv-Dativ, plural, nearticulat', 'SP'),
(107, 'Substantiv propriu, Nominativ-Acuzativ, singular, articulat', 'SP'),
(108, 'Substantiv propriu, Genitiv-Dativ, singular, articulat', 'SP'),
(109, 'Substantiv propriu, Nominativ-Acuzativ, plural, articulat', 'SP'),
(110, 'Substantiv propriu, Genitiv-Dativ, plural, articulat', 'SP'),
(111, 'Substantiv propriu, Formă necunoscută', 'SP');
unlock tables;


lock tables `Prefixes` write;
insert into `Prefixes` (`id`,`form`, `formUtf8General`, `prefixLength`) values
(1, 'a', 'a', 1),
(2, 'an', 'an', 2),
(3, 'ambi', 'ambi', 4),
(4, 'ante', 'ante', 4),
(5, 'anti', 'anti', 4),
(6, 'anto', 'anto', 4),
(7, 'antropo', 'antropo', 7),
(8, 'arhi', 'arhi', 4),
(9, 'atot', 'atot', 4),
(10, 'auto', 'auto', 4),
(11, 'avan', 'avan', 4),
(12, 'bine', 'bine', 4),
(13, 'bio', 'bio', 3),
(14, 'centri', 'centri', 6),
(15, 'co', 'co', 2),
(16, 'con', 'con', 3),
(17, 'contra', 'contra', 6),
(18, 'crono', 'crono', 5),
(19, 'cvasi', 'cvasi', 5),
(20, 'des', 'des', 3),
(21, 'dez', 'dez', 3),
(22, 'dis', 'dis', 3),
(23, 'diz', 'diz', 3),
(24, 'de', 'de', 2),
(25, 'di', 'di', 2),
(26, 'demo', 'demo', 4),
(27, 'dia', 'dia', 3),
(28, 'echi', 'echi', 4),
(29, 'endo', 'endo', 4),
(30, 'exo', 'exo', 3),
(31, 'extra', 'extra', 5),
(32, 'entero', 'entero', 6),
(33, 'entomo', 'entomo', 6),
(34, 'epi', 'epi', 3),
(35, 'eso', 'eso', 3),
(36, 'eu', 'eu', 2),
(37, 'euro', 'euro', 4),
(38, 'filo', 'filo', 4),
(39, 'fito', 'fito', 4),
(40, 'geronto', 'geronto', 7),
(41, 'giro', 'giro', 4),
(42, 'heli', 'heli', 4),
(43, 'hemi', 'hemi', 4),
(44, 'semi', 'semi', 4),
(45, 'hetero', 'hetero', 6),
(46, 'etero', 'etero', 5),
(47, 'homo', 'homo', 4),
(48, 'homeo', 'homeo', 5),
(49, 'omo', 'omo', 3),
(50, 'hemo', 'hemo', 4),
(51, 'hidro', 'hidro', 5),
(52, 'higro', 'higro', 5),
(53, 'hidroxo', 'hidroxo', 7),
(54, 'hiper', 'hiper', 5),
(55, 'hipo', 'hipo', 6),
(56, 'holo', 'holo', 7),
(57, 'homi', 'homi', 4),
(58, 'hecto', 'hecto', 5),
(59, 'hepato', 'hepato', 6),
(60, 'ultra', 'ultra', 5),
(61, 'între', 'între', 5),
(62, 'inter', 'inter', 5),
(63, 'intra', 'intra', 5),
(64, 'intro', 'intro', 5),
(65, 'bari', 'bari', 4),
(66, 'anemo', 'anemo', 5),
(67, 'extra', 'extra', 5),
(68, 'extro', 'extro', 5),
(69, 'izo', 'izo', 3),
(70, 'iso', 'iso', 3),
(71, 'mega', 'mega', 4),
(72, 'melo', 'melo', 4),
(73, 'meta', 'micro', 4),
(74, 'mezo', 'mezo', 4),
(75, 'multi', 'multi', 5),
(76, 'poli', 'poli', 4),
(77, 'pluri', 'pluri', 5),
(78, 'macro', 'macro', 5),
(79, 'micro', 'micro', 5),
(80, 'mnemo', 'mnemo', 5),
(81, 'morfo', 'morfo', 5),
(82, 'nano', 'nano', 4),
(83, 'ne', 'ne', 4),
(84, 'nitro', 'nitro', 5),
(85, 'neuro', 'neuro', 5),
(86, 'nefro', 'nefro', 5),
(87, 'neo', 'neo', 3),
(88, 'novo', 'novo', 4),
(89, 'gineco', 'gineco', 6),
(90, 'paleo', 'paleo', 5),
(91, 'proto', 'proto', 5),
(92, 'pseudo', 'pseudo', 6),
(93, 'orto', 'orto', 4),
(94, 'oligo', 'oligo', 5),
(95, 'oliga', 'oliga', 5),
(98, 'oxi', 'oxi', 3),
(99, 'omni', 'omni', 4),
(100, 'octo', 'octo', 4),
(101, 'ovo', 'ovo', 3),
(102, 'chino', 'chino', 5),
(103, 'chimio', 'chimio', 6),
(104, 'fizio', 'fizio', 5),
(105, 'pan', 'pan', 3),
(106, 'pedo', 'pedo', 4),
(107, 'peda', 'peda', 4),
(108, 'psiho', 'psiho', 5),
(109, 'socio', 'socio', 5),
(110, 'steno', 'steno', 5),
(111, 'post', 'post', 4),
(112, 'pre', 'pre', 3),
(113, 'peri', 'peri', 4),
(114, 'prea', 'prea', 4),
(115, 'petro', 'petro', 5),
(116, 'patro', 'patro', 5),
(117, 'ptero', 'ptero', 5),
(118, 'psihro', 'psihro', 6),
(119, 'pato', 'pato', 4),
(120, 'quasi', 'quasi', 5),
(121, 'radio', 'radio', 5),
(122, 'răs', 'răs', 3),
(123, 'răz', 'răz', 3),
(124, 're', 're', 2),
(125, 'retro', 'retro', 5),
(126, 'ruso', 'ruso', 4),
(127, 'rău', 'rău', 3),
(128, 'rino', 'rino', 4),
(129, 'andro', 'andro', 5),
(130, 'oto', 'oto', 3),
(131, 'oftalmo', 'oftalmo', 7),
(133, 'sin', 'sin', 3),
(134, 'sim', 'sim', 3),
(135, 'sino', 'sino', 4),
(136, 'sexo', 'sexo', 4),
(137, 'super', 'super', 5),
(138, 'stră', 'stră', 4),
(139, 'stereo', 'stereo', 6),
(140, 'sub', 'sub', 3),
(141, 'supra', 'supra', 5),
(142, 'sine', 'sine', 4),
(143, 'sub', 'sub', 3),
(144, 'iono', 'iono', 4),
(145, 'magneto', 'magneto', 7),
(146, 'electro', 'electro', 7),
(147, 'tehno', 'tehno', 5),
(148, 'trans', 'trans', 5),
(149, 'tera', 'tera', 4),
(150, 'kilo', 'kilo', 4),
(151, 'deci', 'deci', 4),
(152, 'mega', 'mega', 4),
(153, 'miria', 'miria', 5),
(154, 'kineto', 'kineto', 6),
(158, 'deca', 'deca', 4),
(159, 'bi', 'bi', 2),
(160, 'cvadri', 'cvadri', 6),
(161, 'tri', 'tri', 3),
(162, 'dodeca', 'dodeca', 6),
(163, 'fero', 'fero', 4),
(164, 'sexa', 'sexa', 4),
(165, 'hexa', 'hexa', 4),
(166, 'tetra', 'tetra', 5),
(167, 'centi', 'centi', 5),
(168, 'osteo', 'osteo', 5),
(169, 'peta', 'peta', 4),
(170, 'zero', 'zero', 4),
(171, 'pico', 'pico', 4),
(172, 'femto', 'femto', 5),
(173, 'atto', 'atto', 4),
(174, 'zepto', 'zepto', 5),
(175, 'yocto', 'yocto', 5),
(176, 'ihtio', 'ihtio', 5),
(177, 'ego', 'ego', 3),
(178, 'agro', 'agro', 4),
(179, 'centro', 'centro', 6),
(180, 'api', 'api', 3),
(181, 'acva', 'acva', 4),
(182, 'ego', 'ego', 3),
(183, 'neutro', 'neutro', 6),
(184, 'ftizio', 'ftizio', 6),
(185, 'acvi', 'acvi', 4),
(186, 'histo', 'histo', 5),
(187, 'infra', 'infra', 5);
unlock tables;

lock tables `Suffixes` write;
insert into `Suffixes` (`id`,`form`, `formUtf8General`, `suffixLength`) values
(1, 'agiu', 'agiu', 4),
(2, 'egiu', 'egiu', 4),
(3, 'ugiu', 'ugiu', 4),
(4, 'aj', 'aj', 2),
(5, 'ej', 'ej', 2),
(6, 'andru', 'andru', 5),
(7, 'iune', 'iune', 4),
(8, 'ie', 'ie', 2),
(9, 'iciu', 'iciu', 4),
(10, 'abil', 'abil', 4),
(11, 'ibil', 'ibil', 4),
(12, 'ubil', 'ubil', 4),
(13, 'ace', 'ace', 3),
(14, 'aie', 'aie', 3),
(15, 'țial', 'țial', 4),
(16, 'țional', 'țional', 6),
(17, 'ean', 'ean', 3),
(18, 'ian', 'ian', 3),
(19, 'an', 'an', 2),
(20, 'ent', 'ent', 3),
(21, 'anță', 'anță', 4),
(22, 'ență', 'ență', 4),
(23, 'ință', 'ință', 4),
(24, 'ar', 'ar', 2),
(25, 'al', 'al', 2),
(26, 'are', 'are', 3),
(27, 'ere', 'ere', 3),
(28, 'ire', 'ire', 3),
(29, 'arh', 'arh', 3),
(30, 'arhie', 'arhie', 5),
(31, 'at', 'at', 2),
(32, 'et', 'et', 2),
(33, 'it', 'it', 2),
(34, 'ut', 'ut', 2),
(35, 'autică', 'autică', 6),
(36, 'eutică', 'eutică', 6),
(37, 'ază', 'ază', 3),
(38, 'eză', 'eză', 3),
(39, 'iză', 'iză', 3),
(40, 'bilitate', 'bilitate', 8),
(41, 'cefal', 'cefal', 5),
(42, 'ces', 'ces', 3),
(43, 'cid', 'cid', 3),
(44, 'crat', 'crat', 4),
(45, 'crație', 'crație', 6),
(46, 'cron', 'cron', 4),
(47, 'cul', 'cul', 3),
(48, 'culă', 'culă', 4),
(49, 'dinte', 'dinte', 5),
(50, 'ea', 'ea', 2),
(51, 'eag', 'eag', 3),
(52, 'iag', 'iag', 3),
(53, 'og', 'og', 2),
(54, 'eală', 'eală', 4),
(55, 'ială', 'ială', 4),
(56, 'ean', 'ean', 3),
(57, 'ee', 'ee', 2),
(58, 'enie', 'enie', 4),
(59, 'esc', 'esc', 3),
(60, 'ește', 'ește', 4),
(61, 'estru', 'estru', 5),
(62, 'et', 'et', 2),
(63, 'ime', 'ime', 3),
(64, 'ectomie', 'ectomie', 7),
(65, 'tate', 'tate', 4),
(66, 'tură', 'tură', 4),
(67, 'at', 'at', 2),
(68, 'etă', 'etă', 3),
(69, 'et', 'et', 2),
(70, 'ețe', 'ețe', 3),
(71, 'eu', 'eu', 2),
(72, 'fag', 'fag', 3),
(73, 'vor', 'vor', 3),
(74, 'fil', 'fil', 3),
(75, 'filie', 'filie', 5),
(76, 'fit', 'fit', 3),
(77, 'fob', 'fob', 3),
(78, 'fon', 'fon', 3),
(79, 'fonie', 'fonie', 5),
(80, 'form', 'form', 4),
(81, 'fug', 'fug', 3),
(82, 'gen', 'gen', 3),
(83, 'genie', 'genie', 5),
(84, 'graf', 'graf', 4),
(85, 'grafie', 'grafie', 6),
(86, 'scop', 'scop', 4),
(87, 'scopie', 'scopie', '6'),
(88, 'gram', 'gram', 4),
(89, 'gramă', 'gramă', 5),
(90, 'ibilitate', 'ibilitate', 9),
(91, 'ic', 'ic', 2),
(92, 'ier', 'ier', 3),
(93, 'ieră', 'ieră', 4),
(94, 'il', 'il', 2),
(95, 'im', 'im', 2),
(96, 'in', 'in', 2),
(97, 'iot', 'iot', 3),
(98, 'ism', 'ism', 3),
(99, 'ist', 'ist', 3),
(100, 'istă', 'istă', 4),
(101, 'lniță', 'lniță', 5),
(102, 'rniță', 'rniță', 5),
(103, 'iș', 'iș', 2),
(104, 'iște', 'iște', 4),
(105, 'itudine', 'itudine', 7),
(106, 'iță', 'iță', 3),
(107, 'uță', 'uță', 3),
(108, 'iv', 'iv', 2),
(109, 'log', 'log', 3),
(110, 'gie', 'gie', 3),
(111, 'mânt', 'mânt', 4),
(112, 'ment', 'ment', 4),
(113, 'mente', 'mente', 5),
(114, 'morf', 'morf', 4),
(115, 'nic', 'nic', 3),
(116, 'nim', 'nim', 3),
(117, 'onim', 'onim', 4),
(118, 'oar', 'oar', 3),
(119, 'uar', 'uar', 3),
(120, 'oare', 'oare', 4),
(121, 'oriu', 'oriu', 4),
(122, 'or', 'or', 2),
(123, 'os', 'os', 2),
(124, 'țional', 'țional', 6),
(125, 'țial', 'țial', 4),
(126, 'tură', 'tură', 4),
(127, 'ui', 'ui', 2),
(128, 'ual', 'ual', 3),
(129, 'uu', 'uu', 2),
(130, 'nom', 'nom', 3),
(131, 'nomie', 'nomie', 5),
(132, 'grafie', 'grafie', 6),
(133, 'term', 'term', 4),
(134, 'norm', 'norm', 4),
(135, 'atru', 'atru', 4),
(136, 'acru', 'acru', 4),
(137, 'ație', 'ație', 4);
unlock tables;

lock tables `Domains` write;
insert into `Domains` (`id`,`name`) values
(1, 'astronomie'),
(2, 'astrologie'),
(3, 'matematică'),
(4, 'biologie'),
(5, 'zoologie'),
(6, 'botanică'),
(7, 'fizică'),
(8, 'informatică'),
(9, 'geometrie'),
(10, 'geologie'),
(11, 'geografie'),
(12, 'psihologie'),
(13, 'medicină'),
(14, 'jurnalism'),
(15, 'drept'),
(16, 'religie'),
(17, 'istorie'),
(18, 'sociologie'),
(19, 'pedagogie'),
(20, 'chimie'),
(21, 'electronică'),
(22, 'electrotehnică'),
(23, 'agricultură'),
(24, 'horticultură'),
(25, 'zootehnie'),
(26, 'zoologie'),
(27, 'filologie'),
(28, 'filozofie'),
(29, 'politologie'),
(30, 'biochimie'),
(31, 'bioinformatică'),
(33, 'antropologie'),
(34, 'psihiatrie'),
(35, 'cardiologie'),
(36, 'neurologie'),
(37, 'urologie'),
(38, 'otorinolaringologie'),
(39, 'oftalmologie'),
(40, 'hematologie'),
(41, 'histologie'),
(42, 'psihiatrie'),
(43, 'pediatrie'),
(44, 'odontologie'),
(45, 'stomatologie'),
(46, 'farmacologie'),
(47, 'hermeneutică'),
(48, 'mecanică'),
(49, 'arhitectură'),
(50, 'estetică'),
(51, 'teatrologie'),
(52, 'cinematografie'),
(53, 'neonatologie'),
(54, 'economie'),
(55, 'logică');
unlock tables;

lock tables `Clitics` write;
insert into `Clitics` (`id`, `form`, `formNoHyphen`, `formNoDia`) values
(1, 's-a', 'sa', 's-a'),
(2, 'c-a', 'ca', 'c-a'),
(3, 'n-a', 'na', 'n-a'),
(4, 'i-a', 'ia', 'i-a'),
(5, 'ți-a', 'ția', 'ti-a'),
(6, 'și-a', 'șia', 'si-a'),
(7, 'm-a', 'ma', 'm-a'),
(8, 'l-a', 'la', 'l-a'),
(9, 's-ar', 'sar', 's-ar'),
(10, 'c-ar', 'car', 'c-ar'),
(11, 'n-ar', 'nar', 'n-ar'),
(12, 'i-ar', 'iar', 'i-ar,'),
(13, 'și-ar', 'șiar', 'si-ar'),
(14, 'ți-ar', 'țiar', 'ti-ar'),
(15, 'mi-ar', 'miar', 'mi-ar'),
(16, 'mi-a', 'mia', 'mi-a'),
(17, 'le-a', 'lea', 'le-a'),
(18, 'le-ar', 'lear', 'le-ar'),
(19, 'ne-a', 'nea', 'ne-a'),
(20, 'v-a', 'va', 'v-a'),
(21, 'v-ar', 'var', 'v-ar'),
(22, 's-au', 'sau', 's-au'),
(23, 'm-au', 'mau', 'm-au'),
(24, 'ți-au', 'țiau', 'ti-au'),
(25, 'i-au', 'iau', 'i-au'),
(26, 'le-au', 'leau', 'le-au'),
(27, 'ne-au', 'neau', 'ne-au'),
(28, 'și-au', 'șiau', 'si-au'),
(29, 'l-au', 'lau', 'l-au'),
(30, 'v-au', 'vau', 'v-au'),
(31, 'te-au', 'teau', 'te-au'),
(32, 'te-a', 'tea', 'te-a'),
(33, 'te-ar', 'tear', 'te-ar'),
(34, 'c-au', 'cau', 'c-au'),
(35, 'c-am', 'cam', 'c-am'),
(36, 'l-am', 'lam', 'l-am'),
(37, 'i-am', 'iam', 'i-m'),
(38, 'le-am', 'leam', 'le-m'),
(39, 'v-am', 'vam', 'v-m'),
(40, 'mi-am', 'mi-am', 'mi-m'),
(41, 'ți-am', 'țiam', 'ti-m'),
(42, 'te-am', 'team', 'te-m'),
(43, 'mi-aș', 'miaș', 'mi-s'),
(44, 'ți-aș', 'ți-aș', 'ti-s'),
(45, 'te-aș', 'teaș', 'te-s'),
(46, 'v-aș', 'vaș', 'v-s'),
(47, 'le-aș', 'leaș', 'le-s'),
(48, 'i-aș', 'i-aș', 'i-s'),
(49, 'm-aș', 'maș', 'm-s'),
(50, 'c-aș', 'caș', 'c-s'),
(51, 'l-aș', 'laș', 'l-s'),
(52, 'ne-aș', 'neaș', 'ne-s'),
(53, 'ne-am', 'neam', 'ne-am'),
(54, 'n-aș', 'naș', 'n-as'),
(58, 'n-am', 'nam', 'n-am'),
(59, 'n-au', 'nau', 'n-au'),
(60, 'de-aș', 'deaș', 'de-as'),
(61, 'de-am', 'deam', 'de-am'),
(62, 'de-ar', 'dear', 'de-ar'),
(63, 'de-au', 'deau', 'de-au'),
(64, 'de-a', 'dea', 'de-a'),
(65, 'm-ai', 'mai', 'm-ai'),
(66, 'te-ai', 'teai', 'te-ai'),
(67, 'l-ai', 'lai', 'l-ai'),
(68, 'mi-ai', 'miai', 'mi-ai'),
(69, 'ți-ai', 'țiai', 'ti-ai'),
(70, 'ne-ai', 'neai', 'ne-ai'),
(71, 'i-ai', 'iai', 'i-ai'),
(72, 'n-ai', 'nai', 'n-ai'),
(73, 'c-ai', 'cai', 'c-ai'),
(74, 'de-ai', 'deai', 'de-ai'),
(75, 'm-ați', 'mați', 'ma-ti'),
(76, 'l-ați', 'lați', 'la-ti'),
(77, 'mi-ați', 'miați', 'mi-ati'),
(78, 'ne-ați', 'neați', 'ne-ati'),
(79, 'v-ați', 'vați', 'v-ati'),
(80, 'i-ați', 'iați', 'i-ati'),
(81, 'și-ați', 'șiați', 'si-ati'),
(82, 'și-ai', 'șiai', 'si-ai'),
(83, 'și-aș', 'șiaș', 'si-as'),
(84, 'c-ați', 'cați', 'ca-ti'),
(85, 'de-ați', 'deați', 'de-ati'),
(86, 'n-ați', 'nați', 'n-ati'),
(87, 'dac-aș', 'dacaș', 'dac-as'),
(88, 'dac-am', 'dacam', 'dac-am'),
(89, 'dac-ai', 'dacai', 'dac-ai'),
(90, 'dac-a', 'daca', 'dac-a'),
(91, 'dac-ar', 'dacar', 'dac-ar'),
(92, 'dac-ați', 'dacați', 'dac-ati'),
(93, 'dac-au', 'dacau', 'dac-au'),
(94, 'dac-o', 'daco', 'dac-o'),
(95, 'c-o', 'co', 'c-o'),
(96, 'n-o', 'no', 'n-o'),
(97, 'și-o', 'șio', 'si-o'),
(98, 'i-o', 'io', 'i-o'),
(99, 'le-o', 'leo', 'le-o'),
(100, 'le-ați', 'leați', 'le-ati'),
(101, 'le-ai', 'leai', 'le-ai'),
(102, 'le-a', 'lea', 'le-a'),
(103, 'mi-o', 'mio', 'mi-o'),
(104, 'ți-o', 'țio', 'ti-o'),
(105, 'v-o', 'vo', 'v-o'),
(106, 's-o', 'so', 's-o'),
(107, 'te-o', 'teo', 'te-o'),
(108, 'mi-oi', 'mioi', 'mi-oi'),
(109, 'ți-oi', 'țioi', 'ti-oi'),
(110, 'm-oi', 'moi', 'm-oi'),
(111, 'te-oi', 'teoi', 'te-oi'),
(112, 'l-oi', 'l-oi', 'l-oi'),
(113, 'i-oi', 'ioi', 'i-oi'),
(114, 'c-oi', 'coi', 'c-oi'),
(115, 'n-oi', 'noi', 'n-oi'),
(116, 'dac-oi', 'dacoi', 'dac-oi'),
(117, 'de-oi', 'deoi', 'de-oi'),
(118, 'și-oi', 'șioi', 'si-oi'),
(119, 'ne-om', 'neom', 'ne-om'),
(120, 'v-om', 'vom', 'v-om'),
(121, 'le-om', 'leom', 'le-om'),
(122, 'te-om', 'teom', 'te-om'),
(123, 'l-om', 'lom', 'l-om'),
(124, 'i-om', 'iom', 'i-om'),
(125, 'ți-om', 'țiom', 'ti-om'),
(126, 'c-om', 'com', 'c-om'),
(127, 'n-om', 'nom', 'n-om'),
(129, 'dac-om', 'dacom', 'dac-om'),
(130, 'de-om', 'deom', 'de-om'),
(131, 'și-om', 'și-om', 'si-om'),
(132, 'mi-or', 'mi-or', 'mi-or'),
(133, 'm-or', 'mor', 'm-or'),
(134, 'te-or', 'teor', 'te-or'),
(135, 'ți-or', 'țior', 'ti-or'),
(136, 'l-or', 'lor', 'l-or'),
(138, 'ne-or', 'neor', 'ne-or'),
(139, 'v-or', 'vor', 'v-or'),
(140, 'și-or', 'șior', 'si-or'),
(141, 'le-or', 'le-or', 'le-or'),
(142, 'i-or', 'ior', 'i-or'),
(143, 'c-or', 'cor', 'c-or'),
(144, 'n-or', 'nor', 'n-or'),
(145, 'dac-or', 'dacor', 'dac-or'),
(146, 'm-îți', 'mîți', 'm-iti'),
(147, 'mi-îți', 'miîți', 'mi-iti'),
(148, 'l-îți', 'lîți', 'l-iti'),
(149, 'ne-îți', 'neîți', 'ne-iti'),
(150, 'i-îți', 'iîți', 'i-iti'),
(151, 'le-îți', 'leîți', 'le-iti'),
(152, 'și-îți', 'șiîți', 'si-iti'),
(153, 'n-îți', 'nîți', 'n-iti'),
(154, 'c-îți', 'cîți', 'c-iti'),
(155, 'dac-îi', 'dacîi', 'dac-ii'),
(156, 'm-îi', 'mîi', 'm-ii'),
(157, 'mi-îi', 'miîi', 'mi-ii'),
(158, 'l-îi', 'lîi', 'l-ii'),
(159, 'ne-îi', 'neîi', 'ne-ii'),
(160, 'i-îi', 'iîi', 'i-ii'),
(161, 'le-îi', 'leîi', 'le-ii'),
(162, 'și-îi', 'șiîi', 'si-ii'),
(163, 'n-îi', 'nîi', 'n-ii'),
(164, 'c-îi', 'cîi', 'c-ii'),
(165, 'dac-îi', 'dacîi', 'dac-ii'),
(166, 'ți-îi', 'țiîi', 'ti-ii'),
(167, 'v-îți', 'vîți', 'v-iti'),
(168, 'să-mi', 'sămi', 'sa-mi'),
(169, 'să-ți', 'săți', 'sa-ti'),
(170, 'să-și', 'săși', 'sa-si'),
(171, 'să-i', 'săi', 'sa-i'),
(172, 'pe-un', 'peun', 'pe-un'),
(173, 'pe-o', 'peo', 'pe-o'),
(174, 'pe-unui', 'peunui', 'pe-unui'),
(175, 'pe-unor', 'peunor', 'pe-unor'),
(176, 'pe-unora', 'peunora', 'pe-unora'),
(177, 'pe-unei', 'peunei', 'pe-unei'),
(178, 'pe-unele', 'peunele', 'pe-unele'),
(179, 'de-un', 'deun', 'de-un'),
(181, 'de-unui', 'deunui', 'de-unui'),
(182, 'de-unor', 'deunor', 'de-unor'),
(183, 'de-unora', 'deunora', 'de-unora'),
(184, 'de-unei', 'deunei', 'de-unei'),
(185, 'de-unele', 'deunele', 'de-unele'),
(186, 'lâng-un', 'lângun', 'lang-un'),
(187, 'lâng-o', 'lângo', 'lang-o'),
(188, 'într-un', 'întrun', 'intr-un'),
(189, 'într-o', 'întro', 'intr-o'),
(190, 'într-una', 'întruna', 'intr-una'),
(191, 'printr-un', 'printrun', 'printr-un'),
(192, 'printr-o', 'printro', 'printr-o'),
(193, 'printr-una', 'printruna', 'printr-una'),
(194, 'dintr-un', 'dintrun', 'dintr-un'),
(195, 'dintr-o', 'dintro', 'dintr-o'),
(196, 'dintr-una', 'dintruna', 'dintr-una'),
(197, 'de-una', 'deuna', 'de-una'),
(198, 'pe-una', 'peuna', 'pe-una'),
(199, 'ca-n', 'can', 'ca-n'),
(200, 'dacă-n', 'dacăn', 'daca-n'),
(201, 'c-un', 'cun', 'c-un'),
(202, 'c-una', 'cuna', 'c-una'),
(203, 'pentr-un', 'pentrun', 'pentr-un'),
(204, 'pentr-o', 'pentro', 'pentr-o'),
(205, 'pentr-una', 'pentruna', 'pentr-una'),
(206, 'mă-sa', 'măsa', 'ma-sa'),
(207, 'mă-sii', 'măsii', 'ma-sii'),
(208, 'ta-su', 'tasu', 'ta-su'),
(209, 'tac-su', 'tacsu', 'tac-su'),
(210, 'tac-tu', 'tactu', 'tac-tu'),
(211, 'ta-tu', 'tatu', 'ta-tu'),
(212, 'taică-său', 'taicăsău', 'taica-sau'),
(213, 'taică-su', 'taicăsu', 'taica-su'),
(214, 'taică-meu', 'taicămeu', 'taica-meu'),
(215, 'maică-mea', 'maicămea', 'maica-mea'),
(216, 'maică-ta', 'maicăta', 'maica-ta'),
(217, 'maică-sa', 'maicăsa', 'maica-sa'),
(218, 'fi-ți-ar', 'fițiar', 'fi-ti-ar'),
(219, 'fi-mi-ar', 'fimiar', 'fi-mi-ar'),
(220, 'fi-v-ar', 'fivar', 'fi-v-ar'),
(221, 'fi-le-ar', 'filear', 'fi-le-ar'),
(222, 'fi-r-ar', 'firar', 'fi-r-ar'),
(223, 'd-zeu', 'dzeu', 'd-zeu'),
(224, 'făr-un', 'fărun', 'far-un'),
(225, 'făr-o', 'făro', 'far-o'),
(226, 'peste-un', 'pesteun', 'peste-un'),
(227, 'peste-o', 'pesteo', 'peste-o'),
(228, 'dup-un', 'dupun', 'dup-un'),
(229, 'dup-o', 'dupo', 'dup-o'),
(230, 'către-un', 'cătreun', 'catre-un'),
(231, 'către-o', 'cătreo', 'catre-o'),
(232, 'de-ale', 'deale', 'de-ale'),
(233, 'de-alor', 'dealor', 'de-alor'),
(234, 'd-lui', 'dlui', 'd-lui'),
(235, 'd-lor', 'dlor', 'd-lor'),
(237, 'd-nei', 'dnei', 'd-nei'),
(238, 'd-rei', 'drei', 'd-rei'),
(239, 'd-ta', 'dta', 'd-ta'),
(240, 'd-ei', 'dei', 'd-ei'),
(241, 'd-sale', 'dsale', 'd-sale'),
(242, 'd-tale', 'dtale', 'd-tale'),
(243, 'să-l', 'săl', 'sal'),
(244, 'că-și', 'căși', 'casi'),
(245, 'că-l', 'căl', 'cal'),
(246, 'că-n', 'căn', 'can'),
(247, 'ca-ntr-o', 'cantro', 'ca-ntr-o'),
(248, 'ca-ntr-un', 'cantrun', 'ca-ntr-un'),
(249, 'ca-ntr-una', 'cantruna', 'ca-ntr-una'),
(250, 'că-ntr-o', 'căntro', 'ca-ntr-o'),
(251, 'că-ntr-un', 'căntrun', 'ca-ntr-un'),
(252, 'că-ntr-una', 'căntruna', 'ca-ntr-una'),
(253, 'și-n', 'șin', 'si-n'),
(254, 'și-l', 'șil', 'si-l'),
(255, 'și-și', 'șiși', 'si-si'),
(256, 'și-ntr-o', 'șintro', 'si-ntr-o'),
(257, 'și-ntr-un', 'șintrun', 'si-ntr-un'),
(258, 'și-ntr-una', 'șintruna', 'si-ntr-una'),
(259, 'și-ți', 'șiți', 'si-ti'),
(260, 'și-i', 'șii', 'si-i'),
(261, 'asta-i', 'astai', 'asta-i'),
(262, 'aia-i', 'aiai', 'aia-i'),
(263, 'ăsta-i', 'ăstai', 'asta-i'),
(264, 'ăia-s', 'ăias', 'aia-s'),
(265, 'ăștia-s', 'ăștias', 'astia-s'),
(266, 'asteas-s', 'asteas', 'astea-s'),
(267, 'ăla-i', 'ăla-i', 'alai'),
(268, 'alea-s', 'aleas', 'aleas'),
(269, 'că-s', 'căs', 'ca-s'),
(270, 'eu-s', 'eus', 'eu-s'),
(271, 'dacă-s', 'dacăs', 'dacas'),
(272, 'și-s', 'șis', 'sis'),
(273, 'ba-s', 'bas', 'bas'),
(274, 'nu-s', 'nus', 'nus'),
(275, 'de-al', 'deal', 'de-al'),
(276, 'pe-al', 'peal', 'pe-al'),
(277, 'pe-ale', 'peale', 'pe-ale'),
(278, 'pe-alor', 'pealor', 'pe-alor'),
(279, 'ci-n', 'cin', 'ci-n'),
(280, 'ci-ntr-o', 'cintro', 'ci-ntr-o'),
(281, 'ci-ntr-un', 'cintrun', 'ci-ntr-un'),
(282, 'ci-ntr-una', 'cintruna', 'ci-ntr-una'),
(283, 'ba-i', 'bai', 'bai');
unlock tables;


lock tables `CliticTokens` write;
insert into `CliticTokens` (`id`,`form`, `formNoDia`) values
(1, 's', 's'),
(2, 'i', 'i'),
(3, 'o', 'o'),
(4, 'ți', 'ti'),
(5, 'și', 'si'),
(6, 'un', 'un'),
(7, 'ntr', 'ntr'),
(8, 'v', 'v'),
(9, 'l', 'l'),
(10, 'ba', 'ba'),
(11, 'n', 'n'),
(12, 'm', 'm'),
(13, 'mi', 'mi'),
(14, 'ne', 'ne'),
(15, 'vă', 'va'),
(16, 'mă', 'ma'),
(17, 'te', 'te'),
(18, 'le', 'le'),
(19, 'meu', 'meu'),
(20, 'tău', 'tău'),
(21, 'său', 'său'),
(22, 'dac', 'dac'),
(23, 'într', 'intr'),
(24, 'printr', 'printr'),
(25, 'dintr', 'dintr'),
(26, 'să', 'sa'),
(27, 'se', 'se'),
(28, 'de', 'de'),
(29, 'pe', 'pe'),
(30, 'al', 'al'),
(31, 'ai', 'ai'),
(32, 'a', 'a'),
(33, 'ale', 'ale'),
(34, 'alui', 'alui'),
(35, 'alor', 'alor'),
(36, 'ăsta', 'asta'),
(37, 'ăla', 'ala'),
(38, 'ăia', 'aia'),
(39, 'aia', 'aia'),
(40, 'alea', 'alea'),
(41, 'ăst', 'ast'),
(42, 'ast', 'ast'),
(43, 'fi', 'fi'),
(44, 'am', 'am'),
(45, 'ai', 'ai'),
(46, 'are', 'are'),
(47, 'ați', 'ati'),
(48, 'ar', 'ar'),
(49, 'aș', 'as'),
(50, 'oi', 'oi'),
(51, 'îi', 'ii'),
(52, 'îți', 'iti'),
(53, 'unui', 'unui'),
(54, 'unei', 'unei'),
(55, 'unor', 'unor'),
(56, 'unu', 'unu'),
(57, 'doi', 'doi'),
(58, 'trei', 'trei'),
(59, 'patru', 'patru'),
(60, 'cinci', 'cinci'),
(61, 'șase', 'sase'),
(62, 'șapte', 'sapte'),
(63, 'opt', 'opt'),
(64, 'nouă', 'noua'),
(65, 'zece', 'zece'),
(66, 'două', 'două'),
(67, 'unsprezece', 'unsprezece'),
(68, 'doisprezece', 'doisprezece'),
(69, 'douăsprezece', 'douăsprezece'),
(70, 'treisprezece', 'treisprezece'),
(71, 'paisprezece', 'paisprezece'),
(72, 'patrusprezece', 'patrusprezece'),
(73, 'cincisprezece', 'cincisprezece'),
(74, 'șaisprezece', 'saisprezece'),
(75, 'șaptesprezece', 'saptesprezece'),
(76, 'optsprezece', 'optsprezece'),
(77, 'nouăsprezece', 'nouasprezece');
unlock tables;
